@startuml

[*] --> Parent

state StateB

state Parent {
    [*] -> StateA

    state EXIT_1 <<exitPoint>>
    StateA -> EXIT_1: EVENT_2
    StateA -> [*]: EVENT_3

    EXIT_1 --> StateB: ON_EXIT_1
}

Parent --> StateC: EVENT_3


@enduml