@startuml

[*] -> Parent
Parent --> StateC: E2
Parent -[bold,#Green]-> StateD #LightGreen: **E3**

state Parent {
    state Final1 <<end>>

    [*] -> StateA
    StateA -> StateB #Orange: E1
    StateB -[bold,#Green]-> Final1: **E2**
    note left of Final1
        final state emits
        E3 event on entry
    end note
}

@enduml
